version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - .:/docker-entrypoint-initdb.d
    env_file:
      - "dbDocker.env"
    ports:
      - "5430:5432"

  goscrapper:
    build: ./
    command: go run ./GoScrapper/main.go
    env_file:
      - "dbDocker.env"
    depends_on:
      - postgres

  goapi:
    build: ./
    command: go run ./main.go
    ports:
      - "8089:8089"
    env_file:
      - "dbDocker.env"
    depends_on:
      - postgres
