version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - .:/docker-entrypoint-initdb.d
    env_file:
      - "dbDocker.env"
    ports:
      - "5430:5432"

  nginx:
    image: nginx:latest
    ports:
    - "3409:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
    - postgres
    - goapi

  goscrapper:
    build: ./goscrapper
    command: go run ./main.go
    env_file:
      - "dbDocker.env"
    depends_on:
      - postgres

  goapi:
    build: ./
    command: go run ./main.go
    ports:
      - "8089:8089"
    env_file:
      - "dbDocker.env"
    depends_on:
      - postgres
